### ISSUE TITLE
Feature: Additional Plugins

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot-lab#26]
Does it make since to include some default plugins here such as:

nautobot-capacity-metrics
nautobot-chatops
nautobot-device-onboarding
nautobot-golden-config

**Comment by jtdub** [comment]
Absolutely! I'll look into getting those added!

**Comment by gmoisio** [comment]
Hi all, the idea was good. Has someone an idea about a release date?
Thanks
Regards

**Comment by deku-m** [comment]
Any news when this is implemented?
As the pull request is there?
