### ISSUE TITLE
supervisord problem

### ISSUE THREAD

**Issue by breedjaram** [nautobot/nautobot-lab#39]
Hi,
when I deployed autobot docker image from https://hub.docker.com/r/networktocode/nautobot-lab via gitlab to Kubernetes.
Image not works 
`
Error: could not read config file /etc/supervisord.conf
For help, use /usr/local/bin/supervisord -h
`
When run image locally in docker so works fine.

**Comment by nniehoff** [comment]
@breedjaram the lab image is not specifically designed to work in Kubernetes.  As mentioned in the README of this project this container is *NOT* for production use.  I suggest you take a look at the [official Nautobot container ](https://nautobot.readthedocs.io/en/latest/docker/) for more information.
