### ISSUE TITLE
Nautobot 2.2.0 Default User Setup Fails

### ISSUE THREAD

**Issue by kingfetty** [nautobot/nautobot-lab#93]
Nautobot Version 2.2.0

When the Ansible script executes default_user.py  to seed the default 'demo' user, it throws an exception as nautobot.setup() method no longer exists. 

 @glennmatthews  suggested to remove the django.setup() and nautobot.setup() calls and instead of invoking default_user.py via python3 executable to invoke via 'nautobot-server runscript ./templates/default_user.py/templates/default_user.py', but this throws an error with not able to load the modules with relative paths.  

Tried the same method with absolute paths but get an exception as well.

**Comment by glennmatthews** [comment]
Given nautobot/nautobot#5531, we're likely going to reintroduce the `nautobot.setup()` function in 2.2.1. Stay tuned!

**Comment by glennmatthews** [comment]
2.2.1 will include the fix.
